---
title: "Chal2"
author: "Ram Nimmakayala"
date: "9/23/2018"
output: html_document
---

---
title: "Challenge1"
author: "Ram Nimmakayala"
date: "9/23/2018"
output: html_document
---

**This is the report for the _gapminder_ dataset for _life expectancy_ plot**


```{r, echo=FALSE}

rm(list= ls())

#location of the data
filename <- "Data/gapminder.txt"

#read the data file
library(ggplot2)
gapdata <- read.table(file = filename, header = TRUE)
canadadata <-gapdata[gapdata$country == "Canada",]

ggplot(data = canadadata, aes(x = year, y = lifeExp)) + geom_line()


```


```{r, results='hide',eval=FALSE}
### Run this code in R to see graphic of how
### your document gets rendered
par(mar=rep(0, 4), bty="n", cex=1.5)
plot(0, 0, type="n", xlab="", ylab="", xaxt="n", yaxt="n",
     xlim=c(0, 100), ylim=c(0, 100))
xw <- 10
yh <- 35
xm <- 12
ym <- 50
rect(xm-xw/2, ym-yh/2, xm+xw/2, ym+yh/2, lwd=2)
text(xm, ym, ".Rmd")

xm <- 50
ym <- 80
rect(xm-xw/2, ym-yh/2, xm+xw/2, ym+yh/2, lwd=2)
text(xm, ym, ".md")
xm <- 50; ym <- 25
for(i in c(2, 0, -2))
    rect(xm-xw/2+i, ym-yh/2+i, xm+xw/2+i, ym+yh/2+i, lwd=2,
         border="black", col="white")
text(xm-2, ym-2, "figs/")

xm <- 100-12
ym <- 50
rect(xm-xw/2, ym-yh/2, xm+xw/2, ym+yh/2, lwd=2)
text(xm, ym, ".html")

arrows(22, 50, 38, 50, lwd=2, col="slateblue", len=0.1)
text((22+38)/2, 60, "knitr", col="darkslateblue", cex=1.3)

arrows(62, 50, 78, 50, lwd=2, col="slateblue", len=0.1)
text((62+78)/2, 60, "pandoc", col="darkslateblue", cex=1.3)
```

The average of the class is 44.07777884.`r round(44.07777884,2)`
